CREATE DATABASE EMPRESA;
GO

-- DROP DATABASE EMPRESA;

USE EMPRESA;
GO

CREATE TABLE tb_DEPARTAMENTO (
	COD_DEPTO	TINYINT IDENTITY(1, 1),
	DEPTO		VARCHAR(50)	NOT NULL

	CONSTRAINT pk_DEPARTAMENTO_codDPTO PRIMARY KEY (COD_DEPTO),
	CONSTRAINT uq_DEPARTAMENTO_DEPTO UNIQUE (DEPTO)
)

CREATE TABLE tb_CARGO (
	COD_CARGO	TINYINT IDENTITY(10, 1),
	CARGO		VARCHAR(50) NOT NULL,
	SALARIO_INC	SMALLMONEY NOT NULL
	
	CONSTRAINT pk_CARGO_codCARGO PRIMARY KEY (COD_CARGO),
	CONSTRAINT uq_CARGO_CARGO UNIQUE (CARGO)
)

CREATE TABLE tb_EMPREGADO (
	CODFUN			SMALLINT IDENTITY(1000, 1),
	NOME			VARCHAR(50) NOT NULL,
	NUM_DEPEND		TINYINT NOT NULL,
	DATA_NASCIMENTO	DATE NOT NULL,
	COD_DEPTO		TINYINT NOT NULL,
	COD_CARGO		TINYINT NOT NULL,
	DATA_ADMISSAO	DATE NOT NULL,
	SALARIO			SMALLMONEY NOT NULL,
	PREMIO_MENSAL	SMALLMONEY NOT NULL,
	SINDICALIZADO	BIT NOT NULL,
	OBS				VARCHAR(150),
	FOTO			VARCHAR(300),
	COD_SUPERVISOR	TINYINT

	CONSTRAINT pk_EMPREGADO_codFUN		PRIMARY KEY (CODFUN),
	CONSTRAINT fk_EMPREGADO_codDEPTO	FOREIGN KEY (COD_DEPTO) REFERENCES tb_DEPARTAMENTO (COD_DEPTO),
	CONSTRAINT fk_EMPREGADO_codCARGO	FOREIGN KEY (COD_CARGO) REFERENCES tb_CARGO (COD_CARGO),
)

CREATE TABLE tb_DEPENDENTE (
	CODFUN			SMALLINT NOT NULL,
	CODDEP			TINYINT NOT NULL,
	NOME			VARCHAR(50) NOT NULL,
	DATA_NASCIMENTO	DATE NOT NULL

	CONSTRAINT fk_DEPENTENDE_codFUN FOREIGN KEY (CODFUN) REFERENCES tb_EMPREGADO (CODFUN)
)

INSERT tb_CARGO (CARGO, SALARIO_INC) VALUES ('ANALISTA', 2500.00)
INSERT tb_CARGO (CARGO, SALARIO_INC) VALUES ('OPERADOR', 2000.00)
INSERT tb_CARGO (CARGO, SALARIO_INC) VALUES ('GERENTE', 7000.00)
INSERT tb_CARGO (CARGO, SALARIO_INC) VALUES ('SUPERVISOR', 3500.00)
INSERT tb_CARGO (CARGO, SALARIO_INC) VALUES ('SECRETARIADO', 3000.00)


INSERT tb_DEPARTAMENTO (DEPTO) VALUES ('OPERAÇÃO')
INSERT tb_DEPARTAMENTO (DEPTO) VALUES ('PRODUÇÃO')
INSERT tb_DEPARTAMENTO (DEPTO) VALUES ('TI')
INSERT tb_DEPARTAMENTO (DEPTO) VALUES ('RH')
INSERT tb_DEPARTAMENTO (DEPTO) VALUES ('GERENCIA')


INSERT tb_EMPREGADO (NOME,NUM_DEPEND,DATA_NASCIMENTO,COD_DEPTO,COD_CARGO,DATA_ADMISSAO,SALARIO,PREMIO_MENSAL,SINDICALIZADO)
VALUES ('JOSÉ', 2, '01/01/1980', 1, 11, '01/01/2000', 2200.00, 500.00, 1)
INSERT tb_EMPREGADO (NOME,NUM_DEPEND,DATA_NASCIMENTO,COD_DEPTO,COD_CARGO,DATA_ADMISSAO,SALARIO,PREMIO_MENSAL,SINDICALIZADO)
VALUES ('CAIO', 0, '01/01/1990', 3, 10, '01/01/2020', 3000.00, 1500.00, 0)
INSERT tb_EMPREGADO (NOME,NUM_DEPEND,DATA_NASCIMENTO,COD_DEPTO,COD_CARGO,DATA_ADMISSAO,SALARIO,PREMIO_MENSAL,SINDICALIZADO)
VALUES ('JABA', 1, '01/01/1960', 2, 13, '01/01/2010', 3700, 500.00, 1)
INSERT tb_EMPREGADO (NOME,NUM_DEPEND,DATA_NASCIMENTO,COD_DEPTO,COD_CARGO,DATA_ADMISSAO,SALARIO,PREMIO_MENSAL,SINDICALIZADO)
VALUES ('MATIAS', 1, '01/01/1970', 4, 14, '01/01/2000', 4000.00, 500.00, 0)
INSERT tb_EMPREGADO (NOME,NUM_DEPEND,DATA_NASCIMENTO,COD_DEPTO,COD_CARGO,DATA_ADMISSAO,SALARIO,PREMIO_MENSAL,SINDICALIZADO)
VALUES ('ALBERTO', 1, '01/01/1980', 5, 12, '01/01/2008', 8000.00, 2000.00, 0)


INSERT tb_DEPENDENTE (CODFUN, CODDEP, NOME, DATA_NASCIMENTO) VALUES (1000, 1, 'MARIA', '01/01/2000')
INSERT tb_DEPENDENTE (CODFUN, CODDEP, NOME, DATA_NASCIMENTO) VALUES (1000, 1, 'JOAO', '01/01/2000')
INSERT tb_DEPENDENTE (CODFUN, CODDEP, NOME, DATA_NASCIMENTO) VALUES (1002, 2, 'MARIA', '01/01/2000')
INSERT tb_DEPENDENTE (CODFUN, CODDEP, NOME, DATA_NASCIMENTO) VALUES (1003, 4, 'MARIA', '01/01/2000')
INSERT tb_DEPENDENTE (CODFUN, CODDEP, NOME, DATA_NASCIMENTO) VALUES (1004, 5, 'MARIA', '01/01/2000')


SELECT * FROM tb_CARGO
SELECT * FROM tb_DEPARTAMENTO
SELECT * FROM tb_DEPENDENTE
SELECT * FROM tb_EMPREGADO